### ISSUE TITLE
[PE-D][Tester C] `Fitadd` command: Format validation for random text after specifying default supported prefixes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T17-3/tp#280]
Input:
1. `fitadd 1 /arms /something`
1. `fitadd 1 /arms abcdefg`
1. `fitadd 1 /arms s/ r/ b`

Expected: Error message specifying invalid arguments.
Actual: Command succeeds.

Problems: This bug allows users to input `fitadd 1 /arms /leg` _(note the typo of `/leg` instead of `/legs`)_, and it will succeed without any error, while the `/legs` exercises are not added.

Note the 3rd input too, that the command accepts `s/`, `r/` and `b/` prefixes.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: shaunlxw/ped#16

**Comment by jjchee77** [comment]
This issue is because of the current logic in `FitAddCommandParser.java` and `FitDeleteCommandParser.java`.

Currently, there is a check to ensure that the `name` argument cannot be simultaneously supplied with the default supported prefixes. Apart from that, any other form of prefixes or text is ignored by the parsers.

Unless it violates the feature freeze, the proposed solution is to update the user guide to mention that any other forms of prefixes or text is ignored.

**Comment by dillontkh** [comment]
make command fail if any invalid prefix is used?
